<!-- sidebar -->

<!-- DO NOT EDIT THIS FILE, his automtically genereted from wordpress ( appereance->widget - Sidebar)-->

<aside class="sidebar col-sm-3 col-md-3" role="complementary">

	<div class="sidebar-widget side-content">
		<?php if(!function_exists('dynamic_sidebar') || !dynamic_sidebar('sidebar-1')) ?>
	</div>

</aside>

<!-- /sidebar -->